[package]
name = "crabs_pipes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
macroquad-tiled = "0.1.1"

[profile.dev.package.'*']
opt-level = 3
